models:
  - name: bronze_parking_violation_codes
    description: Raw data representing the violation codes and their fees.
    columns:
      - name: violation_code
        description: '{{ doc("violation_code")}}'
      - name: definition
        description: Description of the violation for a respective code.
      - name: manhattan_96th_st_below
        description: The fee in $USD for a violation on or below Manhattan 96th Street.
      - name: all_other_areas
        description: The fee in $USD for a violation not on or below Manhattan 96th Street.
  - name: bronze_parking_violations
    description: Raw data for parking violations
    columns:
      - name: violation_code
        description: '{{ doc("violation_code")}}'
      - name: summons_number
        tests:
           - unique
           - not_null